apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.scaler.io
spec:
  group: scaler.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  default-minReplicas:
                    type: integer                      
                  schedules:
                    type: array
                    items:
                      type: object
                      properties:
                        start:
                          type: string
                        scale-type:
                          type: string
                          enum:
                            - "custom"
                            - "hourly"                          
                        total-duration:
                          type: object
                          properties:
                            hours:
                              type: integer
                            minutes:
                              type: integer
                        scale-duration:
                          type: object
                          properties:
                            minutes:
                              type: integer                          
                        target-minReplicas:
                          type: integer
                        days:
                          type: array
                          items:
                            type: string
                            enum:
                            - "monday"
                            - "tuesday"
                            - "wednesday"
                            - "thursday"
                            - "friday"
                            - "saturday"
                            - "sunday"
                            - "weekday"
                            - "weekend"
                            - "everyday"
  scope: Namespaced
  names:
    plural: schedules
    singular: schedule
    kind: Schedule
    shortNames:
    - sch

    